import * as React from 'react';
import MovieListSection from '../organisms/MovieListSection';

const datas = [
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
  {
    adult: false,
    backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    genre_ids: [28, 12, 878],
    id: 100402,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Captain America: The Winter Soldier',
    overview:
      'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
    popularity: 69.864,
    poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    release_date: '2014-03-20',
    title: 'Captain America: The Winter Soldier',
    video: false,
    vote_average: 7.7,
    vote_count: 16271,
  },
];

export default function MovieListLayout() {
  return <MovieListSection datas={datas} types="list" />;
}
